name: Publish Docker image to ghcr.io public repository

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
on:
  push:
#     branches:
#     - master
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: push-to-ghcr
      uses: macbre/push-to-ghcr@v0.0.1
