# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code linter and tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://github.com/actions/python-versions/blob/main/versions-manifest.json
        # https://devguide.python.org/versions/
        python-version:
        - "3.9"  # EOL at the end of 2025
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: python-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test
